project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /template/rpcs3_template.ts
    translation: /translations/rpcs3_%two_letters_code%.ts